name: Manual Workflow

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display Branches and PR Title
        run: |
          echo "Compare Branch: dxgfhed"
          echo "PR Title: dhdhg"
          echo "Merge Status: dghdgh"
