name: Manual Send Release Event to Noibu

on:
  workflow_dispatch:
    inputs:
      component:
        type: string
        description: 'Component name'
        required: true
      title:
        type: string
        description: 'Title -Summary of the release-'
        required: true
      description:
        type: string
        description: 'Description -Details about the release. Value can be “null”-'
        required: true
      status:
        type: choice
        description: 'Status'
        options: 
         - success
         - failled
      version:
        type: string
        description: 'Version -ticket ID-'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Display Inputs
        run: |
          echo "Component: ${{ github.event.inputs.component }}"
          echo "Title: ${{ github.event.inputs.title }}"
          echo "Description: ${{ github.event.inputs.description }}"
          echo "Status: ${{ github.event.inputs.status }}"
          echo "Version: ${{ github.event.inputs.version }}"
