name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      component:
        type: string
        description: 'Component name'
        required: true
      title:
        type: string
        description: 'Title of the message'
        required: true
      description:
        type: string
        description: 'Description of the message'
        required: true
      status:
        type: string
        description: 'Status of the message'
        required: true
      version:
        type: string
        description: 'Version of the message'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Display Inputs
        run: |
          echo "Component: ${{ github.event.inputs.component }}"
          echo "Title: ${{ github.event.inputs.title }}"
          echo "Description: ${{ github.event.inputs.description }}"
          echo "Status: ${{ github.event.inputs.status }}"
          echo "Version: ${{ github.event.inputs.version }}"
